-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE public.employees
(
    employee_id integer NOT NULL,
	user_id integer,
    job_position_id integer,
	verify_id integer,
	company_name character varying(255),
	tax_number character varying(255),
	website_name character varying(255),
    phone_number character varying(255),
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
	user_id integer,
	job_position_id integer,
    first_name character varying(255),
    last_name character varying(255),
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.job_positions
(
    job_position_id integer NOT NULL,
    job_position_name character varying(255),
    PRIMARY KEY (job_position_id)
);

CREATE TABLE public.job_sekeers
(
    job_sekeer_id integer NOT NULL,
	user_id integer,
	job_position_id integer,
	verify_id integer,
	nationality_id bigint,
    first_name character varying(255),
    last_name character varying(255),
	date_of_birth date,
    PRIMARY KEY (job_sekeer_id)
);

CREATE TABLE public.users
(
    user_id integer NOT NULL,
	user_name character varying(255),
    email character varying(255),
    password character varying(255),
    PRIMARY KEY (user_id)
);

CREATE TABLE public.verify
(
    verify_id integer NOT NULL,
	user_id integer,
	verified boolean,
    email_verified boolean,
	verify_date date,
    PRIMARY KEY (verify_id)
);

ALTER TABLE public."employees"
    ADD FOREIGN KEY ("job_position_id")
    REFERENCES public."job_positions" ("job_position_id")
    NOT VALID;


ALTER TABLE public."employees"
    ADD FOREIGN KEY ("user_id")
    REFERENCES public."users" ("user_id")
    NOT VALID;


ALTER TABLE public."employees"
    ADD FOREIGN KEY ("verify_id")
    REFERENCES public."verify" ("verify_id")
    NOT VALID;


ALTER TABLE public."employers"
    ADD FOREIGN KEY ("job_position_id")
    REFERENCES public."job_positions" ("job_position_id")
    NOT VALID;


ALTER TABLE public."employers"
    ADD FOREIGN KEY ("user_id")
    REFERENCES public."users" ("user_id")
    NOT VALID;


ALTER TABLE public."job_sekeers"
    ADD FOREIGN KEY ("job_position_id")
    REFERENCES public."job_positions" ("job_position_id")
    NOT VALID;


ALTER TABLE public."job_sekeers"
    ADD FOREIGN KEY ("user_id")
    REFERENCES public."users" ("user_id")
    NOT VALID;


ALTER TABLE public."job_sekeers"
    ADD FOREIGN KEY ("verify_id")
    REFERENCES public."verify" ("verify_id")
    NOT VALID;

END;