-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Employees"
(
    "EmployeeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "JobPositionId" integer NOT NULL,
    "VeriyId" integer NOT NULL,
    "CompanyName" character varying NOT NULL,
    "TaxNumber" character(24) NOT NULL,
    "WebsiteName" character varying NOT NULL,
    "PhoneNumber" character(24) NOT NULL,
    PRIMARY KEY ("EmployeeId")
);

CREATE TABLE public."Employers"
(
    "EmployerId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" integer NOT NULL,
    "JobPositionId" integer NOT NULL,
    "FirstName" character varying NOT NULL,
    "LastName" character varying NOT NULL,
    PRIMARY KEY ("EmployerId")
);

CREATE TABLE public."JobPositions"
(
    "JobPositionId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "JobPositionName" character varying NOT NULL,
    PRIMARY KEY ("JobPositionId")
);

CREATE TABLE public."JobSekeers"
(
    "JobSekeersId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "JobPositionId" integer NOT NULL,
    "VerifyId" integer NOT NULL,
    "FirstName" character varying NOT NULL,
    "LastName" character varying NOT NULL,
    "NationalityId" "char" NOT NULL,
    "DateOfBirth" date NOT NULL,
    PRIMARY KEY ("JobSekeersId")
);

CREATE TABLE public."Users"
(
    "UserId" integer NOT NULL,
    "UserName" character varying NOT NULL,
    "Email" character varying NOT NULL,
    "Password" character varying NOT NULL,
    PRIMARY KEY ("UserId")
);

CREATE TABLE public."Verify"
(
    "VerifyId" integer NOT NULL,
    "Verified" bit(1),
    "UserId" integer,
    "EmailVerified" bit(1),
    "VerifyDate" date,
    PRIMARY KEY ("VerifyId")
);

CREATE TABLE public.employees
(
    employee_id integer NOT NULL,
    company_name character varying(255),
    job_position_id integer,
    phone_number character varying(255),
    tax_number character varying(255),
    user_id integer,
    verify_id integer,
    website_name character varying(255),
    PRIMARY KEY (employee_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    first_name character varying(255),
    last_name character varying(255),
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.job_position
(
    job_position_id integer NOT NULL,
    job_position_name character varying(255),
    PRIMARY KEY (job_position_id)
);

CREATE TABLE public.job_sekeer
(
    job_sekeer_id integer NOT NULL,
    date_of_birth date,
    first_name character varying(255),
    last_name character varying(255),
    nationality_id bigint,
    PRIMARY KEY (job_sekeer_id)
);

CREATE TABLE public.users
(
    user_id integer NOT NULL,
    email character varying(255),
    password character varying(255),
    user_name character varying(255),
    PRIMARY KEY (user_id)
);

CREATE TABLE public.verify
(
    verify_id integer NOT NULL,
    email_verified boolean,
    verified boolean,
    PRIMARY KEY (verify_id)
);

ALTER TABLE public."Employees"
    ADD FOREIGN KEY ("JobPositionId")
    REFERENCES public."JobPositions" ("JobPositionId")
    NOT VALID;


ALTER TABLE public."Employees"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserId")
    NOT VALID;


ALTER TABLE public."Employees"
    ADD FOREIGN KEY ("VeriyId")
    REFERENCES public."Verify" ("VerifyId")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("JobPositionId")
    REFERENCES public."JobPositions" ("JobPositionId")
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserId")
    NOT VALID;


ALTER TABLE public."JobSekeers"
    ADD FOREIGN KEY ("JobPositionId")
    REFERENCES public."JobPositions" ("JobPositionId")
    NOT VALID;


ALTER TABLE public."JobSekeers"
    ADD FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserId")
    NOT VALID;


ALTER TABLE public."JobSekeers"
    ADD FOREIGN KEY ("VerifyId")
    REFERENCES public."Verify" ("VerifyId")
    NOT VALID;

END;